require('dashboard').setup({
    theme = 'doom',
    config = {
  header = {
 	"",
	"",
	" ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗",
	" ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║",
	" ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║",
	" ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║",
	" ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║",
	" ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝",
	"",
	" [ Welcome Back! ] ",
    "",
  },
  center = {
    {
      icon = '󰥔 ',
      icon_hl = 'Title',
      desc = 'Recent Files',
      desc_hl = 'String',
      key = 'r',
      keymap = 'SPC f r',
      key_hl = 'Number',
      action = 'Telescope oldfiles',
    },
    {
      icon = '󰈔 ',
      icon_hl = 'Title',
      desc = 'Find File',
      desc_hl = 'String',
      key = 'f',
      keymap = 'SPC f f',
      key_hl = 'Number',
      action = 'Telescope find_files find_command=rg,--hidden,--files',
    },
    {
      icon = '󰪶 ',
      icon_hl = 'Title',
      desc = 'File Browser',
      desc_hl = 'String',
      key = 'b',
      keymap = 'SPC f b',
      key_hl = 'Number',
      action = 'Telescope file_browser',
    },
    {
      icon = ' ',
      icon_hl = 'Title',
      desc = 'Find Word',
      desc_hl = 'String',
      key = 'g',
      keymap = 'SPC f g',
      key_hl = 'Number',
      action = 'Telescope live_grep',
    },
  },
  footer = { "", "Have a nice day!" },
}
})
