import = ["/home/bubsy/.config/alacritty/themes/catppuccin-frappe.toml"]

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"
